language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - coverage run --source=crowdtruth/ setup.py test
after_success:
  - codecov